#!/bin/sh

abort() {
  echo
  echo "  $@" 1>&2
  echo
  exit 1
}

log() {
  echo "  ○ $@"
}

if [ -e '/etc/init/' ]; then
  log "Installing packages"
  npm install process-watcher
  npm install monitr
  npm install mod_statuspage
  log "Installing upstart config"
  sudo cp ylistener.conf /etc/init/
  status ylistener || sudo start ylistener
fi


