#!/bin/sh

abort() {
  echo
  echo "  $@" 1>&2
  echo
  exit 1
}

log() {
  echo "  ○ $@"
}

log "Installing upstart config"
sudo cp ylistener.conf /etc/init/

status ylistener || sudo start ylistener
